name = "starbin"
type = "webpack"
account_id = "6e8f81ce0e8ba25c184fa66b5fea3ac1"
workers_dev = false
zone_id = "e8f61d23932aca701b7b4d904f039df5"

routes = [
  "https://paste.youhavetrouble.me/raw*",
  "https://paste.youhavetrouble.me/documents*",
]

kv_namespaces = [{ binding = "STORAGE", id = "60ba6d957b8e43e89bb7310975365071" }]
