name = "starbin"
type = "webpack"
account_id = "884ed4928e66a3bdf71e3ed9b4be842a"
workers_dev = false
zone_id = "73bfaa5a503f36239010e58bf5a197fe"

routes = [
  "https://paste.youhavetrouble.me/raw*",
  "https://paste.youhavetrouble.me/documents*",
]

kv_namespaces = [{ binding = "STORAGE", id = "60ba6d957b8e43e89bb7310975365071" }]
